services:
  tarkov-sitcoop-dev:
    build:
      context: .
      args:
        SIT_BRANCH: "development"
        SIT: "HEAD^"
        SPT_BRANCH: "3.9.0-DEV"
        SPT: "HEAD^"
    container_name: sitcoop-dev
    volumes:
      - ./server-dev:/opt/server
    ports:
      - "6969-6972:6969-6972"
    restart: unless-stopped
