services:
  tarkov-sitcoop-dev:
    build:
      context: .
      args:
        SIT_BRANCH: "master"
        SIT: "26b9c364963ba49de71d5761bed1135ddad50f77"
        SPT_BRANCH: "3.8.1-DEV"
        SPT: "a425b1bc4bfe5403b957132dbd678afe4b9f7a21"
    container_name: sitcoop-dev
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./server-dev:/opt/server
    ports:
      - "6969-6972:6969-6972"
    stdin_open: true
    tty: true
    restart: unless-stopped
