services:
  tarkov-sitcoop:
    image: stayintarkov/stayintarkov:latest
    container_name: sitcoop
    environment:
      SIT_BACKEND_IP: 127.0.0.1
    volumes:
      - ./server:/opt/server
    ports:
      - "6969-6972:6969-6972"
    stdin_open: true
    tty: true
    restart: unless-stopped
