services:
  tarkov-sitcoop:
    image: stayintarkov/stayintarkov:latest
    container_name: sitcoop
    volumes:
      - ./server:/opt/server
    ports:
      - "6969-6972:6969-6972"
    restart: unless-stopped
