services:
  tarkov-sitcoop-dev:
    build:
      context: .
      args:
        SIT_BRANCH: "development"
        SIT: "HEAD^"
        SPT_BRANCH: "3.8.1-DEV"
        SPT: "HEAD^"
    container_name: sitcoop-dev
    environment:
      SIT_BACKEND_IP: 127.0.0.1
    volumes:
      - ./server-dev:/opt/server
    ports:
      - "6969-6972:6969-6972"
    stdin_open: true
    tty: true
    restart: unless-stopped
